Fix `flexoki-themes` submodule (#6436)
This PR fixes an issue with the `flexoki-themes` submodule.

When trying to initialize the submodule, we are seeing the following
error:

```
λ just init-submodule extensions/flexoki-themes
git submodule update --init --recursive extensions/flexoki-themes
fatal: remote error: upload-pack: not our ref 8d723bac4a9ac46adfdf99d42155286977aac72a
fatal: Fetched in submodule path 'extensions/flexoki-themes', but it did not contain 8d723bac4a9ac46adfdf99d42155286977aac72a. Direct fetching of that commit failed.
error: Recipe `init-submodule` failed on line 11 with exit code 128
```

I think the issue stems from the switch from
https://github.com/oddship/zed-flexoki-theme to
https://github.com/kepano/flexoki at some point, but am having trouble
tracking down exactly where things went awry.